/**
 * BackendSnapshotEngine.ts
 * Auto compilation service creating secure, signed balance snapshots.
 * Signs compiled blocks using HMAC-SHA256 with server-managed secrets.
 */

import * as crypto from "crypto";
import { ReplayStateResult } from "./BackendReplayAuthority";

export interface LedgerSnapshot {
  snapshotId: string;
  tenantId: string;
  compiledBalance: number;
  upToTimestamp: number;
  transactionCount: number;
  compiledHash: string; // The rolling hash of the last replayed node
  hmacSignature: string; // HMAC-SHA256 signature assuring snapshot authenticity
  createdAt: number;
}

export class BackendSnapshotEngine {
  private static SNAPSHOT_SECRET = process.env.SNAPSHOT_SIGNING_SECRET || "PUMPAI-SNAPSHOT-SECURE-KEY-2026-PRODUCTION-HASH";

  /**
   * Compiles replayed balance results into a signed snapshot rollup
   */
  public static compileSnapshot(
    replayResult: ReplayStateResult,
    upToTimestamp: number
  ): LedgerSnapshot {
    const snapshotId = `SNAP-${replayResult.tenantId}-${Date.now()}`;
    const createdAt = Date.now();

    // Prepare structural string to sign
    const signaturePayload = [
      snapshotId,
      replayResult.tenantId,
      replayResult.calculatedBalance.toFixed(2),
      upToTimestamp.toString(),
      replayResult.totalTransactionsProcessed.toString(),
      replayResult.finalHash,
      createdAt.toString()
    ].join("|");

    // Generate HMAC-SHA256
    const hmacSignature = crypto
      .createHmac("sha256", this.SNAPSHOT_SECRET)
      .update(signaturePayload)
      .digest("hex");

    return {
      snapshotId,
      tenantId: replayResult.tenantId,
      compiledBalance: replayResult.calculatedBalance,
      upToTimestamp,
      transactionCount: replayResult.totalTransactionsProcessed,
      compiledHash: replayResult.finalHash,
      hmacSignature,
      createdAt
    };
  }

  /**
   * Cryptographically verifies if a snapshot rollup was generated by an authorized system key
   */
  public static verifySnapshotSignature(snapshot: LedgerSnapshot): boolean {
    const signaturePayload = [
      snapshot.snapshotId,
      snapshot.tenantId,
      snapshot.compiledBalance.toFixed(2),
      snapshot.upToTimestamp.toString(),
      snapshot.transactionCount.toString(),
      snapshot.compiledHash,
      snapshot.createdAt.toString()
    ].join("|");

    const calculatedHmac = crypto
      .createHmac("sha256", this.SNAPSHOT_SECRET)
      .update(signaturePayload)
      .digest("hex");

    return calculatedHmac === snapshot.hmacSignature;
  }
}
