"use strict";
/**
 * BackendSnapshotEngine.ts
 * Auto compilation service creating secure, signed balance snapshots.
 * Signs compiled blocks using HMAC-SHA256 with server-managed secrets.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.BackendSnapshotEngine = void 0;
const crypto = __importStar(require("crypto"));
class BackendSnapshotEngine {
    static { this.SNAPSHOT_SECRET = process.env.SNAPSHOT_SIGNING_SECRET || "PUMPAI-SNAPSHOT-SECURE-KEY-2026-PRODUCTION-HASH"; }
    /**
     * Compiles replayed balance results into a signed snapshot rollup
     */
    static compileSnapshot(replayResult, upToTimestamp) {
        const snapshotId = `SNAP-${replayResult.tenantId}-${Date.now()}`;
        const createdAt = Date.now();
        // Prepare structural string to sign
        const signaturePayload = [
            snapshotId,
            replayResult.tenantId,
            replayResult.calculatedBalance.toFixed(2),
            upToTimestamp.toString(),
            replayResult.totalTransactionsProcessed.toString(),
            replayResult.finalHash,
            createdAt.toString()
        ].join("|");
        // Generate HMAC-SHA256
        const hmacSignature = crypto
            .createHmac("sha256", this.SNAPSHOT_SECRET)
            .update(signaturePayload)
            .digest("hex");
        return {
            snapshotId,
            tenantId: replayResult.tenantId,
            compiledBalance: replayResult.calculatedBalance,
            upToTimestamp,
            transactionCount: replayResult.totalTransactionsProcessed,
            compiledHash: replayResult.finalHash,
            hmacSignature,
            createdAt
        };
    }
    /**
     * Cryptographically verifies if a snapshot rollup was generated by an authorized system key
     */
    static verifySnapshotSignature(snapshot) {
        const signaturePayload = [
            snapshot.snapshotId,
            snapshot.tenantId,
            snapshot.compiledBalance.toFixed(2),
            snapshot.upToTimestamp.toString(),
            snapshot.transactionCount.toString(),
            snapshot.compiledHash,
            snapshot.createdAt.toString()
        ].join("|");
        const calculatedHmac = crypto
            .createHmac("sha256", this.SNAPSHOT_SECRET)
            .update(signaturePayload)
            .digest("hex");
        return calculatedHmac === snapshot.hmacSignature;
    }
}
exports.BackendSnapshotEngine = BackendSnapshotEngine;
